### ISSUE TITLE
Re-using matrix factorization

### ISSUE THREAD

**Issue by nrontsis** [bodono/scs-python#1]
Hi,

I believe that the python interface does not allow re-using the matrix factorization. Is this something you plan to support? Would it be difficult to implement?

Thanks,

Nikitas

**Comment by bodono** [comment]
Currently that isn't supported, is it something that would be useful to you? I don't think it would be difficult to implement, if you have a PR I would be happy to merge it in.

**Comment by nrontsis** [comment]
Hey, thanks for the reply. 

Yes it makes sense for my problem, as I am solving a set of parametric problems.

I don't have any experience with connecting C with python. I plan though on working on similar problems related to OSQP, so I might come back with a PR at a future point. For now, I am closing the issue.

**Comment by bodono** [comment]
I'm going to re-open so we can track this.

**Comment by bamos** [comment]
This would be easy to add with only Python using #11 now

**Comment by nrontsis** [comment]
Thanks @bamos; this should cover my needs. @bodono do you think that this should be closed now?

**Comment by bodono** [comment]
Yep, I'll close it now! Thanks all.
