### ISSUE TITLE
scs-python version 2.1.1 fails to install

### ISSUE THREAD

**Issue by dvillega** [bodono/scs-python#19]
The `2.1.1` tar release includes the directory `python_linsys`. This causes the package to not install. This directory is not included in the `2.1.0` release, and removing it from the `2.1.1` tar fixes the install.

The specific error we see is
```
python_linsys/private.c:4:21: fatal error: private.h: No such file or directory
  compilation terminated.
  error: Command "x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DPYTHON -DCTRLC=1 -DDLONG=1 -DPYTHON_LINSYS -DUSE_LAPACK -DHAVE_CBLAS -DHAVE_CBLAS -Iscs/include -Iscs/linsys -Ipython_linsys -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c python_linsys/private.c -o build/temp.linux-x86_64-2.7/python_linsys/private.o -O3" failed with exit status 1
```

Would you publish a new tar without the extraneous directory?

**Comment by dvillega** [comment]
Looks like the tarball is missing the `.h` file. If they *were* intended to be included I think we need to republish with that file as well.

**Comment by bodono** [comment]
Thanks for letting me know, I just reuploaded with that file included. Please test it out and let me know if it's working.

**Comment by bodono** [comment]
Have confirmation that it works now.

**Comment by dvillega** [comment]
Thank you for the quick fix!
