### ISSUE TITLE
Release v2.1.2

### ISSUE THREAD

**Issue by h-vetinari** [bodono/scs-python#22]
It seems that everything is ready (scs-submodule [merged](https://github.com/bodono/scs-python/commit/ed126c280159abcbf6e14677d3ae7227e06c6483), CI passing on master), but there's nothing on [PyPI](https://pypi.org/project/scs/), nor a [release](https://github.com/bodono/scs-python/releases), [tag](https://github.com/bodono/scs-python/tags) or [branch](https://github.com/bodono/scs-python/branches) in this repo.

**Comment by bodono** [comment]
Just uploaded 2.1.2 to PyPi, sorry for the delay.

**Comment by h-vetinari** [comment]
Thanks! :)
