### ISSUE TITLE
Numpy no longer supports MacOS Accelerate framework

### ISSUE THREAD

**Issue by kmonson** [bodono/scs-python#32]
Currently when I try to install scs from source or via pip I get the following error:

RuntimeError: Found /usr/lib/libcblas.dylib, but that file is a symbolic link to the MacOS Accelerate framework, which is not supported by NumPy. You must configure the build to use a different optimized library, or disable the use of optimized BLAS and LAPACK by setting the environment variables NPY_BLAS_ORDER="" and NPY_LAPACK_ORDER="" before building NumPy.

Setting those environment variables does not help.
I've also tried:
export LDFLAGS="-L/usr/local/opt/openblas/lib"
export CPPFLAGS="-I/usr/local/opt/openblas/include"

BLAS=/usr/local/opt/openblas/lib/ python setup.py install --scs
BLAS=/usr/local/opt/openblas/lib/libopenblas.dylib python setup.py install --scs

Nothing seems to make any difference. Is there a workaround for this or is it a bug scs or something else?

**Comment by kmonson** [comment]
I figured out that I could set BLAS_LAPACK_LIB_PATHS to make it work. Is this documented anywhere?

**Comment by bodono** [comment]
What version of numpy / python / mac os are you using? Also what does it say when you type in python:
```
import numpy
from numpy.distutils.system_info import get_info
numpy.show_config()
print(get_info('blas_opt'))
print(get_info('blas'))
print(get_info('lapack_opt'))
print(get_info('lapack'))
```

**Comment by bstellato** [comment]
This seems to help in a new environment
```
brew install openblas

OPENBLAS="$(brew --prefix openblas)" pip install scs
```

**Comment by bodono** [comment]
Thanks @bstellato ! I have updated the readme with a comment on this.
