### ISSUE TITLE
Unable to clone SCS-Python from command line

### ISSUE THREAD

**Issue by wmakarewicz** [bodono/scs-python#34]
#### When attempting to clone SCS Python, I received a "fatal: reference is not a tree:" error relating to the submodule scs after typing the command on two separate systems.
[abc ~]$  git clone --recursive https://github.com/bodono/scs-python.git

#### The command and error message is below. 

Cloning into 'scs-python'...
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 564 (delta 19), reused 27 (delta 10), pack-reused 520
Receiving objects: 100% (564/564), 457.15 KiB | 0 bytes/s, done.
Resolving deltas: 100% (331/331), done.
Submodule 'scs' (https://github.com/cvxgrp/scs.git) registered for path 'scs'
Cloning into 'scs'...
remote: Enumerating objects: 239, done.
remote: Counting objects: 100% (239/239), done.
remote: Compressing objects: 100% (160/160), done.
remote: Total 7810 (delta 144), reused 159 (delta 79), pack-reused 7571
Receiving objects: 100% (7810/7810), 2.57 MiB | 0 bytes/s, done.
Resolving deltas: 100% (5232/5232), done.
fatal: reference is not a tree: d9454c2df9eb17d797237291418931bd48035d08
Unable to checkout 'd9454c2df9eb17d797237291418931bd48035d08' in submodule path 'scs'

**Comment by bodono** [comment]
Thanks for letting me know, I just pushed a commit that should fix it.

**Comment by wmakarewicz** [comment]
I am able to check out. Thanks.
