### ISSUE TITLE
Update python version in CI (and migrate to Github actions?)

### ISSUE THREAD

**Issue by h-vetinari** [bodono/scs-python#42]
The current CI is running with the ancient python 3.5 (long dropped by all relevant libraries, even python 3.6 has been dropped by numpy/scipy et. al. already).

This should be upgraded to at least 3.8 or 3.9 (ideally covering several python versions).

Also, it might be worth considering moving away from appveyor, xref #25.

**Comment by bodono** [comment]
Ok, I've just managed to do this, we're using github actions now and we cover linux, mac os, windows and python v3.6, 3.7, 3.8, 3.9.
