### ISSUE TITLE
Homogenize indentation (and avoid non-standard options)

### ISSUE THREAD

**Issue by h-vetinari** [bodono/scs-python#44]
Currently, a bunch of the code here uses an indent of 2 spaces, though sometimes 4 as well. This could be fixed quite simply (if somewhat opinionatedly) by running `black .` and committing the changes.

For the purpose of useful `git blame`-ing, newer versions of git (IIRC >= 2.23) support excluding certain commits from blame.

@bodono, would you be interested in a PR for that?

**Comment by bodono** [comment]
Yes please!
