### ISSUE TITLE
`undefined symbol: dsyevr_`

### ISSUE THREAD

**Issue by paw-lu** [bodono/scs-python#46]
On importing scs I get an `ImportError`:

```sh
% python -m pip install scs
% python
>>> import scs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/users/pawlu/Documents/scratch/scs/.venv/lib/python3.9/site-packages/scs/__init__.py", line 5, in <module>
    import _scs_direct
ImportError: /data/users/pawlu/Documents/scratch/scs/.venv/lib/python3.9/site-packages/_scs_direct.cpython-39-x86_64-linux-gnu.so: undefined symbol: dsyevr_
```

**Comment by bodono** [comment]
This means that SCS is not able to link to the blas/lapack libs as specified by numpy. What do you get when you type
```py
>>> from numpy.distutils.system_info import get_info
>>> get_info('blas_opt')
```
For me I get 
```
{'libraries': ['mkl_rt', 'pthread'], 'library_dirs': ['/Users/bodonoghue/miniconda2/envs/python37/lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['/Users/bodonoghue/miniconda2/envs/python37/include']}
```
Which is telling me what libraries and their locations to link against in order to pull in blas.

**Comment by paw-lu** [comment]
First of all, thanks @bodono for the help!

When I run `get_info` I get:

```pytb
/data/users/pawlu/Documents/scratch/scs/.venv/lib/python3.9/site-packages/numpy/distutils/system_info.py:2026: UserWarning:
    Optimized (vendor) Blas libraries are not found.
    Falls back to netlib Blas library which has worse performance.
    A better performance should be easily gained by switching
    Blas library.
  if self._calc_info(blas):
/tmp/tmp6aea7e80/source.c:1:10: fatal error: cblas.h: No such file or directory
 #include <cblas.h>
          ^~~~~~~~~
compilation terminated.
{'define_macros': [('NO_ATLAS_INFO', 1)], 'libraries': ['blas', 'blas'], 'library_dirs': ['/usr/lib64'], 'include_dirs': ['/usr/local/include']}
```

**Comment by paw-lu** [comment]
[Following some instructions on the SciPy setup](https://scipy.github.io/devdocs/building/linux.html#fedora-26) I ran

```
sudo dnf install gcc-gfortran python3-devel openblas-devel lapack-devel
```

New `get_info` output is 

```pycon
>>> from numpy.distutils.system_info import get_info
>>> get_info('blas_opt')
{'libraries': ['openblas', 'openblas'], 'library_dirs': ['/usr/lib64'], 'language': 'c', 'define_macros': [('HAVE_CBLAS', None)]}
```

But this doesn't seem to solve the original problem

```pycon
>>> import scs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/users/pawlu/Documents/scratch/scs/.venv/lib/python3.9/site-packages/scs/__init__.py", line 5, in <module>
    import _scs_direct
ImportError: /data/users/pawlu/Documents/scratch/scs/.venv/lib/python3.9/site-packages/_scs_direct.cpython-39-x86_64-linux-gnu.so: undefined symbol: dsyevr_
```

**Comment by bodono** [comment]
Ok, once you've done that you probably need to uninstall and reinstall SCS, since it's still pointing to the old information.

By the way, here is how it is done in the workflow (which installs a fresh conda env and then installs SCS and works for Mac, Linux and Windows):

https://github.com/bodono/scs-python/blob/master/.github/workflows/build.yml#L32

**Comment by paw-lu** [comment]
> Ok, once you've done that you probably need to uninstall and reinstall SCS, since it's still pointing to the old information.

Should have made it more explicit, this occurs on a fresh install in a new virtualenv:

```sh
% python -m pip freeze

% python -m pip install scs

% python -c 'import scs'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/users/pawlu/Documents/scratch/scs/.venv/lib/python3.9/site-packages/scs/__init__.py", line 5, in <module>
    import _scs_direct
ImportError: /data/users/pawlu/Documents/scratch/scs/.venv/lib/python3.9/site-packages/_scs_direct.cpython-39-x86_64-linux-gnu.so: undefined symbol: dsyevr_
```

**Comment by paw-lu** [comment]
> By the way, here is how it is done in the workflow (which installs a fresh conda env and then installs SCS and works for Mac, Linux and Windows):

Yeah unfortunatley in this situation conda is not an option for me, so I'm trying my best to replicate it via pyenv, DNF, and pip. Sometimes the package names in DNF that correspond to the conda ones are not obvious to me though.

**Comment by paw-lu** [comment]
Rebuilding python with `PYTHON_CONFIGURE_OPTS="--enable-shared"` seems to fix the issue.

```sh
% env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.9.5
% pyenv shell 3.9.5
% python -m pip install scs
% python -c 'import scs'
```

**Comment by paw-lu** [comment]
Thanks @bodono for the guidance here!

**Comment by bodono** [comment]
Ah ok great, glad you managed to fix it. My next debugging step I was going to ask of you was going to be quite manual so glad this was fixed relatively easily!
