### ISSUE TITLE
SCS fails to build wheel in Mac OS X Big Sur

### ISSUE THREAD

**Issue by yeraydiazdiaz** [bodono/scs-python#49]
## Specifications
- OS: Mac OS X Big Sur
- SCS version: 2.1.2
- Python version: 3.8.6
- Numpy version: 1.21.2
- Scipy version: 1.7.1
- Output of `get_info` print commands as above (if applicable): N/A

## Description

When attempting to `pip install scs=2.1.2` on Mac OS X Big Sur several compilation errors are raised, the most repeated lines are:

- `/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:384:6: note: insert '_Nonnull' if the pointer should never be null`
- `/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:386:41: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]`

See below for a full output.

## Additional information

I tried installing GCC and setting the `CC` environment variable to point to other compilers but I lack the experience in C to understand the issue.

## Output

[scs-pip-install-error.txt](https://github.com/bodono/scs-python/files/7037910/scs-pip-install-error.txt)

**Comment by brantwhisper** [comment]
+1.  I'm experiencing the same issue. Installing from source seems to work.

**Comment by yeraydiazdiaz** [comment]
This issue seems to have gone away after installing the latest update for Big Sur, I am now in version 11.5.2 and `pip install scs==2.1.2` works just fine.
