### ISSUE TITLE
Release tracker 3.0.0

### ISSUE THREAD

**Issue by h-vetinari** [bodono/scs-python#51]
Hey, great to see that scs 3.0.0 has been released, and that the python bindings are coming along too! 🥳 

Since this repo doesn't use tags, I just wanted to open an issue to make it easier to track the release - hope that's OK. :)

**Comment by bodono** [comment]
The python bindings are complete. I haven't cut a pip release yet though because I'm waiting for cvxpy to be compatible (otherwise it could accidentally break many people).

I can make a tag though if that works for you?

**Comment by bodono** [comment]
Just created a 3.0.0 tag and release.

**Comment by h-vetinari** [comment]
Thanks! It's on the way to conda-forge already! 🙃
