### ISSUE TITLE
Running in parallel

### ISSUE THREAD

**Issue by Cerebrock** [bodono/scs-python#6]
I've tried running it in parallel but it takes an order of magnitude more than with parallel = False. Could OpenMP not be enabled? Wouldn't it raise an error? How can I check if it ran in multiple cores?

**Comment by bodono** [comment]
I've just disabled compiling with openmp by default because I was getting a lot of bug reports about not being able to compile. Is this still an issue for you? If it is feel free to reopen this and I can make openmp optional.
