### ISSUE TITLE
_scs_gpu.cpython: image not found

### ISSUE THREAD

**Issue by taktikal17** [bodono/scs-python#8]
Hi,

I am trying to install the gpu version of scs.

` python3 setup.py install --scs --gpu`

`
Namespace(blas64=False, extraverbose=False, float32=False, gpu=True, int32=False, scs=True)
/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/dist.py:332: UserWarning: Normalizing '2.0.2-3' to '2.0.2.post3'
normalized_version,
running install
running bdist_egg
running egg_info
writing scs.egg-info/PKG-INFO
writing dependency_links to scs.egg-info/dependency_links.txt
writing requirements to scs.egg-info/requires.txt
writing top-level names to scs.egg-info/top_level.txt
{'extra_compile_args': ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers'], 'extra_link_args': ['-Wl,-framework', '-Wl,Accelerate'], 'define_macros': [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]}
{'extra_compile_args': ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers'], 'extra_link_args': ['-Wl,-framework', '-Wl,Accelerate'], 'define_macros': [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]}`
`##################################################`
`# failed to compile with OpenMP;                 #`
`# some sections of SCS will not be parallelized. #`
`##################################################`
`scs 2.0.2.post3 is already the active version in easy-install.pth`

`Installed /usr/local/lib/python3.6/site-packages/scs-2.0.2.post3-py3.6-macosx-10.12-x86_64.egg`
`Processing dependencies for scs==2.0.2.post3`
`Searching for scipy==1.1.0`
`Best match: scipy 1.1.0`
`Adding scipy 1.1.0 to easy-install.pth file`

`Using /usr/local/lib/python3.6/site-packages`
`Searching for numpy==1.15.1`
`Best match: numpy 1.15.1`
`Adding numpy 1.15.1 to easy-install.pth file`

`Using /usr/local/lib/python3.6/site-packages`
`Finished processing dependencies for scs==2.0.2.post3`

When I tried to run:

` python3 test/solve_random_cone_prob_gpu.py`

I received an error message:

`Traceback (most recent call last):
  File "test/solve_random_cone_prob_gpu.py", line 75, in <module>
    main()
  File "test/solve_random_cone_prob_gpu.py", line 14, in main
    solve_feasible()
  File "test/solve_random_cone_prob_gpu.py", line 34, in solve_feasible
    sol_i = scs.solve(data, K, gpu=True, **params)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scs-2.0.2.post3-py3.6-macosx-10.12-x86_64.egg/scs/__init__.py", line 58, in solve
    import _scs_gpu
ImportError: dlopen(/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scs-2.0.2.post3-py3.6-macosx-10.12-x86_64.egg/_scs_gpu.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libcudart.9.2.dylib
  Referenced from: /usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scs-2.0.2.post3-py3.6-macosx-10.12-x86_64.egg/_scs_gpu.cpython-36m-darwin.so
  Reason: image not found`

Any idea how this can be fixed?

Thank you in advance.

**Comment by bodono** [comment]
Did you figure something out? If so it might be useful to others if you could tell us how you fixed it.
