### ISSUE TITLE
Release latest SCS-Python

### ISSUE THREAD

**Issue by wkschwartz** [bodono/scs-python#9]
Since the merging of #7, SCS is now much easier to install, especially on Windows. To take advantage of this improvement, I have to install SCS directly from Git rather than through PyPI. In a Pip `requirements.txt` or a `setup.py`, that requires a line like
```
scs @ git+https://github.com/bodono/scs-python.git@bb45c69ce57b1fbb5ab23e02b30549a7e0b801e3
```
(This works in `setup.py` only in Pip 18.1 and above; for older versions of Pip, you must use the `dependency_links` option in the `setup` function.)

If you release bb45c69ce57b1fbb5ab23e02b30549a7e0b801e3 as, say, `scs-v2.0.3` on PyPI (and, if you don't mind, on [GitHub](https://github.com/bodono/scs-python/releases), too), then I could simplify my dependency management by just writing `scs` instead of everything above.

**Comment by Exelscior** [comment]
Any news on when this will be resolved?

**Comment by adithyabsk** [comment]
I can second that @bodono seems to have been uploading the project to pypi. I have a dependant project that is failing because of the prior version's setup.py containing a top-level numpy import.

**Comment by pietrodn** [comment]
The release of a new version of `scs` would also allow users to install [`cvxpy`](https://github.com/cvxgrp/cvxpy) directly:

```
pip install cvxpy
```

instead of:

```
pip install numpy
pip install cvxpy
```

**Comment by bodono** [comment]
Just uploaded 2.1.0.
